name: Metrics Data Dry Run

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-debug.json
          config_output: json
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages
