name: Update Readme Stats

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"
    - cron: "0 21 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: markdown
          filename: README.md
          markdown: ./readme-template.md
          config_output: markdown
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages
          plugin_wakatime_days: 7
